# Generated by Django 4.2.3 on 2025-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnail/'),
        ),
    ]
