# Generated by Django 4.2.3 on 2025-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobpost_benefits_jobpost_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
