# Generated by Django 5.1.5 on 2025-06-07 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_jobpost_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
