# Generated by Django 5.1.4 on 2025-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobpost_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_email',
            field=models.EmailField(default='noemail@gmail.com', max_length=254),
        ),
    ]
