# Generated by Django 4.2.3 on 2025-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobpost_company_contact_jobpost_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_email',
            field=models.EmailField(max_length=254),
        ),
    ]
