# Generated by Django 4.2.3 on 2024-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_text_2_article_bodytext_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bodyimage_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='bodyimage_1_position',
            field=models.CharField(choices=[('above_text_2', 'Above Text 2'), ('below_text_2', 'Below Text 2'), ('above_text_3', 'Above Text 3'), ('below_text_3', 'Below Text 3')], default='above_text_2', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='bodyimage_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='bodyimage_2_position',
            field=models.CharField(choices=[('above_text_2', 'Above Text 2'), ('below_text_2', 'Below Text 2'), ('above_text_3', 'Above Text 3'), ('below_text_3', 'Below Text 3')], default='above_text_3', max_length=20),
        ),
    ]
