# Generated by Django 4.2.3 on 2024-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_bodyimage_1_article_bodyimage_1_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bodyimage_1_position',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bodyimage_2_position',
        ),
    ]
