# Generated by Django 4.2.3 on 2024-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_bodyimage_1_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
