# Generated by Django 4.2.3 on 2024-08-09 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bodyimage_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bodyimage_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bodytext_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bodytext_3',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=120)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='BodyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytext', models.TextField()),
                ('quoted', models.BooleanField(default=False)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('fontzize', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='BodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
