# Generated by Django 4.2.3 on 2024-08-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodytext',
            old_name='fontzize',
            new_name='fontsize',
        ),
    ]
