# Generated by Django 4.2.3 on 2024-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_rename_fontzize_bodytext_fontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyimage',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bodytext',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
    ]
