# Generated by Django 4.2.3 on 2024-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_bodyimage_order_bodytext_order_subtitle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyimage',
            name='order',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bodytext',
            name='order',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='order',
            field=models.CharField(default='', max_length=50),
        ),
    ]
