# Generated by Django 4.2.3 on 2024-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_bodyimage_order_alter_bodytext_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyimage',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='bodytext',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='order',
            field=models.CharField(default='', max_length=50, verbose_name='Order Name'),
        ),
    ]
