# Generated by Django 5.1.5 on 2025-06-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Setting', 'verbose_name_plural': 'Website Settings'},
        ),
    ]
