# Generated by Django 5.1.5 on 2025-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Chief, Career Development & Placement Services', 'Chief, Career Development & Placement Services'), ('Chief, Alumni Relations Services', 'Chief, Alumni Relations Services'), ('Admin Staff 1', 'Admin Staff 1'), ('Admin Staff 2', 'Admin Staff 2'), ('Admin Staff 3', 'Admin Staff 3'), ('Admin Staff 4', 'Admin Staff 4'), ('President', 'President'), ('Executive Vice President', 'Executive Vice President'), ('Vice President for Academic Affairs', 'Vice President for Academic Affairs'), ('Vice President for Student Affairs & Services', 'Vice President for Student Affairs & Services'), ("Vice President for Research, Extension, & Dev't", "Vice President for Research, Extension, & Dev't"), ('Vice President for Branches & Campuses', 'Vice President for Branches & Campuses'), ('Vice President for Administration', 'Vice President for Administration'), ('Vice President for Finance', 'Vice President for Finance')], max_length=100, unique=True),
        ),
    ]
