# Generated by Django 5.1.5 on 2025-06-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_official_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='category',
        ),
    ]
