# Generated by Django 5.1.5 on 2025-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_remove_official_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='arcdo_address',
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='arcdo_address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='arcdo_address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='arcdo_address_line3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='phone_number_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='arcdo_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='linked_in_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='x_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
