# Generated by Django 5.1.5 on 2025-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_remove_websitesettings_arcdo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='bank1_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bank1_account_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bank2_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bank2_account_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='gcash_qr',
            field=models.ImageField(blank=True, null=True, upload_to='user/settings/gcashqr/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='maya_qr',
            field=models.ImageField(blank=True, null=True, upload_to='user/settings/mayaqr/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='paypal_qr',
            field=models.ImageField(blank=True, null=True, upload_to='user/settings/paypalqr/'),
        ),
    ]
