# Generated by Django 5.1.5 on 2025-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_official_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='gcash_qr',
            field=models.ImageField(blank=True, null=True, upload_to='settings/gcashqr/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='maya_qr',
            field=models.ImageField(blank=True, null=True, upload_to='settings/mayaqr/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='paypal_qr',
            field=models.ImageField(blank=True, null=True, upload_to='settings/paypalqr/'),
        ),
    ]
