# Generated by Django 5.1.5 on 2025-06-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Stories', 'verbose_name_plural': 'Stories'},
        ),
    ]
