# Generated by Django 5.1.5 on 2025-06-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_stories_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='stories',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='story_banners/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='story_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
