# Generated by Django 5.1.5 on 2025-06-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_remove_stories_is_active_alter_stories_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stories',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='stories/banners/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/'),
        ),
    ]
