# Generated by Django 5.1.4 on 2025-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
