# Generated by Django 4.2.3 on 2025-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_course_user_certifications_user_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
