# Generated by Django 4.2.3 on 2025-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='school_year',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
