# Generated by Django 4.2.3 on 2025-03-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_section_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='school_year',
        ),
    ]
