# Generated by Django 4.2.3 on 2025-03-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_section_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
