# Generated by Django 4.2.3 on 2025-03-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default=4, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
