# Generated by Django 4.2.3 on 2025-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_section_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=10),
        ),
    ]
