# Generated by Django 4.2.3 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_section_section_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
