# Generated by Django 5.1.5 on 2025-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
