# Generated by Django 4.2.3 on 2025-05-24 18:16

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_events_alter_user_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_profile_image', models.ImageField(default='user/profile_pics/default.jpg', upload_to='user/profile_pics/')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=authentication.models.get_default_profile_image, null=True, upload_to='user/profile_pics/'),
        ),
    ]
