# Generated by Django 5.1.5 on 2025-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_usersettings_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='x_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
