# Generated by Django 4.2.3 on 2025-06-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_year',
            new_name='year_graduated',
        ),
    ]
