# Generated by Django 5.1.4 on 2025-07-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='Developers',
        ),
    ]
