name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: "False"
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

        RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
        RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=: ${{ secrets.POSTGRES_PORT }}
        DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

        EMAIL_HOSTL: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT : ${{ secrets.EMAIL_PORT }}
        EMAIL_USE_TLS : ${{ secrets.EMAIL_USE_TLS }}
        EMAIL_HOST_USER : ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD : ${{ secrets.EMAIL_HOST_PASSWORD }}
        DEFAULT_FROM_EMAIL : ${{ secrets.DEFAULT_FROM_EMAIL }}




